version: '3.8'
services:
  dev-db:
    image: mysql:8.0
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL-PASSWORD: 123456
      MYSQL_DATABASE: nestdb

volumes:
  mysql_volume:
